rudy-patel/imageAnalysisSystem

README.md
=> Added installation steps for windows

README.md
=> Updating README formatting

.gitignore, main.py, templates/base.html, templates/cameras.html, templates/events.html, templates/home.html, templates/train.html, train.html
This PR creates a simple home page with a navbar using bootstrap. Since the navbar routes to different HTML pages, the team can now work in parallel on each page separately.
This closes #40!
=> Creating initial home page with navbar

static/css/style.css, templates/base.html, templates/home.html
This PR deals with the creation of the front-end interface of the home dashboard based on the figma design. Currently there is no functionality on the home page but rather there are placeholder buttons and data that can be configured in the back-end later. This is part of task #16.
Below is what it looks like:
=> Create frontend for home dashboard

main.py, templates/signup.html
This PR prevents duplicate email addresses from creating an account.
See the error message below:
Closes #44.
=> Preventing duplicate email sign up

templates/cameras.html
Title
Again this is just a mockup no functionality is present. closes #18 .
=> Created mockup for camera page

templates/cameras.html, templates/events.html
Title
Similar to PR about Home page, no functionality just placeholder content. closes #17.
=> Created mockup for events page

templates/base.html, templates/events.html, templates/home.html
This PR adds search/filter ability along with pagination to the events table.
Closes #70.
* General search
* Search by column
* Pagination
=> Adding input search fields and pagination to events table

main.py, templates/events.html
In this PR I have connected the table in the events page to the database. This means that the table is dynamic and will respond to changes in the database. The button to "Go to cameras" is not functional and is still just a placeholder, it may be removed in the future. closes #62. 
Screenshot of page with dummy data from db:
=> Connected events table to the database

main.py
=> Removed unused imports

.github/workflows/python-app.yml
=> Removed hardcoded DB_PASSWORD with github secret

main.py
=> Updated queries to order timestamp by descending

.github/workflows/python-app.yml
=> Removed running the auto tests on pushes

static/css/style.css, templates/base.html
=> Reverted navbar to not track what page the user is on

templates/events.html
=> Fixed bug with order being messed up in events table

main.py, models/models.py, requirements.txt, templates/base.html, tests/conftest.py, tests/test_models.py, tests/test_routes.py
This PR extracts the models out of the main file. I also refactored the code to use the Flask factory design pattern, which allows for easier testing of the APIs (we can create separate production + testing versions of the app). A few API tests were also added to extend in the future.
Closes #89.
=> Extracted models + refactored to use Flask factory design pattern

tests/test_routes.py
Just updating the `user_id` so we don't populate the events for our actual test user.
=> Updating user_id in test to push to a dedicated API test user

server/Forms.py, server/main.py, server/templates/events.html, server/templates/train.html
This PR updates the Train page to allow the user to select and label the reference images they are uploading.
Closes #97.
=> Updated training page to allow the user to label the image

tests/test_routes.py
=> Changing api test date to be in the past

server/main.py, server/templates/event_view.html
=> Updated event page to show image and updated timestamp shown

server/templates/events.html
=> Added the name column to the events page

client/client.py, server/main.py
Basic heartbeat between client and server
=> Client heartbeat

tests/test_routes.py
=> Adding test for heartbeat route

server/main.py, server/templates/event_view.html
This PR adds a download button and downloads the file associated with the corresponding event to the user's computer.
Closes #117.
=> Adding download functionality to view event page

server/templates/home.html
=> Updated recent events

client/client.py
=> small client fix

server/main.py
=> Changed time to 24 hour clock

.github/workflows/python-app.yml
=> Added github action for cache

client/client.py, server/main.py
=> Circle event

README.md, docs/database.md, docs/hardware_config.md
Title. Updated README and also created a `/docs` directory just exporting a couple of markdown files from the wiki.
=> Updating docs

server/Forms.py, server/templates/events.html, server/templates/train.html
=> Fixed table sorting bug and removed table from train page

client/client.py, server/Forms.py, server/__init__.py, server/enums/cameraEnums.py, server/enums/eventEnums.py, server/main.py, server/models/models.py, server/server_camera.py, server/templates/base.html, server/templates/cameras.html, server/templates/event_view.html, server/templates/events.html, server/templates/home.html, server/templates/login.html, server/templates/signup.html, server/templates/train.html, simple-client.py, tests/conftest.py, tests/test_enums.py, tests/test_models.py, tests/test_routes.py
Title. The deleted `__init__.py` files were empty, so I assume they are of no use.
=> Adding comments + code cleanup

docs/api.md, server/main.py
=> Adding API Documentation

client/client.py
Changed to Dr. Huda's account.
=> Updated user_id for client HTTP requests
